defmodule Cure.Story.Narrator do
  @moduledoc """
  Template-driven prose and Markdown generator for `cure story` (v0.32.0).

  Takes a `Cure.Story.Outline.outline()` and produces a Markdown narrative
  document introducing the system top-down: apps, supervisors, actors,
  FSMs, then types.

  Mermaid diagrams for FSMs are included when `diagrams: true` is passed.
  """

  alias Cure.Story.Outline

  @doc """
  Generate a Markdown narrative document from a structural outline.

  ## Options

    * `:diagrams` -- when `true`, embed Mermaid state-diagram blocks for
      FSMs. Default: `false`.
    * `:project_name` -- project name for the document title.
      Default: `"Project"`.
  """
  @spec narrate(Outline.outline(), keyword()) :: String.t()
  def narrate(outline, opts \\ []) do
    diagrams? = Keyword.get(opts, :diagrams, false)
    project_name = Keyword.get(opts, :project_name, "Project")

    sections = [
      title_section(project_name),
      overview_section(outline),
      apps_section(outline.apps),
      supervisors_section(outline.supervisors),
      actors_section(outline.actors),
      fsms_section(outline.fsms, diagrams?),
      types_section(outline.types)
    ]

    sections
    |> Enum.reject(&(&1 == ""))
    |> Enum.join("\n\n")
  end

  # -- Sections -----------------------------------------------------------------

  defp title_section(project_name) do
    "# #{project_name}\n\nThis document describes the architecture of the `#{project_name}` system,\ngenerated by `cure story` from the project source."
  end

  defp overview_section(%{apps: apps, supervisors: sups, actors: actors, fsms: fsms, types: types}) do
    parts =
      [
        if(apps != [], do: "#{length(apps)} application(s)", else: nil),
        if(sups != [], do: "#{length(sups)} supervisor(s)", else: nil),
        if(actors != [], do: "#{length(actors)} actor(s)", else: nil),
        if(fsms != [], do: "#{length(fsms)} FSM(s)", else: nil),
        if(types != [], do: "#{length(types)} shared type(s)", else: nil)
      ]
      |> Enum.reject(&is_nil/1)

    if parts == [] do
      "> _No structural components found. Is this a pure-library project?_"
    else
      "## Overview\n\nThe system comprises " <> Enum.join(parts, ", ") <> "."
    end
  end

  defp apps_section([]), do: ""

  defp apps_section(apps) do
    body =
      Enum.map(apps, fn %{name: name, supervisors: sups, actors: actors} ->
        parts = []
        parts = if sups != [], do: parts ++ ["supervisor(s): #{join_names(sups)}"], else: parts
        parts = if actors != [], do: parts ++ ["actor(s): #{join_names(actors)}"], else: parts

        suffix =
          case parts do
            [] -> " It declares no direct children."
            _ -> " It starts " <> Enum.join(parts, " and ") <> "."
          end

        "### `#{name}`\n\nThe `#{name}` application is the root of the system.#{suffix}"
      end)

    "## Applications\n\n" <> Enum.join(body, "\n\n")
  end

  defp supervisors_section([]), do: ""

  defp supervisors_section(sups) do
    body =
      Enum.map(sups, fn %{name: name, strategy: strategy, children: children} ->
        strategy_str = strategy |> to_string() |> String.replace("_", "-")

        children_str =
          case children do
            [] -> " It currently has no declared children."
            kids -> " It manages: #{join_names(kids)}."
          end

        "### `#{name}`\n\nThe `#{name}` supervisor applies a `#{strategy_str}` restart strategy.#{children_str}"
      end)

    "## Supervisors\n\n" <> Enum.join(body, "\n\n")
  end

  defp actors_section([]), do: ""

  defp actors_section(actors) do
    body =
      Enum.map(actors, fn %{name: name, effects: effects, messages: messages} ->
        effects_str =
          case effects do
            [] -> "no declared effects (pure)."
            effs -> "effect(s): #{Enum.join(effs, ", ")}."
          end

        messages_str =
          case messages do
            [] ->
              ""

            msgs ->
              " It handles " <>
                Integer.to_string(length(msgs)) <>
                " message type(s): #{join_names(msgs)}."
          end

        "### `#{name}`\n\nThe `#{name}` actor declares #{effects_str}#{messages_str}"
      end)

    "## Actors\n\n" <> Enum.join(body, "\n\n")
  end

  defp fsms_section([], _diagrams?), do: ""

  defp fsms_section(fsms, diagrams?) do
    body =
      Enum.map(fsms, fn %{name: name, states: states, transitions: transitions} ->
        state_list =
          case states do
            [] -> "no known states"
            ss -> Enum.join(Enum.map(ss, &"`#{&1}`"), ", ")
          end

        transition_count = length(transitions)

        prose =
          "### `#{name}`\n\nThe `#{name}` FSM models " <>
            Integer.to_string(length(states)) <>
            " state(s): #{state_list}. " <>
            Integer.to_string(transition_count) <>
            " transition(s) are defined."

        diagram =
          if diagrams? and transitions != [] do
            "\n\n" <> mermaid_diagram(name, transitions)
          else
            ""
          end

        prose <> diagram
      end)

    "## FSMs\n\n" <> Enum.join(body, "\n\n")
  end

  defp types_section([]), do: ""

  defp types_section(types) do
    items =
      Enum.map(types, fn %{name: name, kind: kind, doc: doc} ->
        kind_str =
          case kind do
            :enum -> "enumeration (ADT)"
            :record -> "record"
            :alias -> "type alias"
          end

        doc_str = if doc, do: " -- #{doc}", else: ""
        "- **`#{name}`** (#{kind_str})#{doc_str}"
      end)
      |> Enum.join("\n")

    "## Shared Types\n\nThe following type definitions are shared across the system:\n\n#{items}"
  end

  # -- Mermaid diagram ----------------------------------------------------------

  defp mermaid_diagram(name, transitions) do
    edges =
      transitions
      |> Enum.map(fn %{from: from, event: event, to: to} ->
        "  #{from} -->|#{event}| #{to}"
      end)
      |> Enum.join("\n")

    "```mermaid\nstateDiagram-v2\n  title #{name}\n#{edges}\n```"
  end

  # -- Helpers ------------------------------------------------------------------

  defp join_names([]), do: "(none)"
  defp join_names([single]), do: "`#{single}`"
  defp join_names([a, b]), do: "`#{a}` and `#{b}`"
  defp join_names([first | rest]), do: "`#{first}`, " <> join_names(rest)
end
