defmodule Cure.Actor.State do
  @moduledoc """
  Runtime-state struct shared by every Cure actor instance.

  Every actor GenServer generated by `Cure.Actor.Compiler` stores a
  single `%Cure.Actor.State{}` as its primary state. Three fields are
  carried:

    * `:caller`  -- the pid that spawned the actor. `notify/1` inside
      `on_message`/`on_start`/`on_stop` bodies targets this pid.
    * `:payload` -- the user-visible domain value. Read via
      `Std.Actor.get_state/1`.
    * `:meta`    -- actor-private bookkeeping.

  Mirrors the shape of `Cure.FSM.State` so lifecycle helpers read the
  same way in both worlds. The module registers the struct in the
  process dictionary (via `register_self/1`) so bare `notify(message)`
  calls inside handler bodies can resolve the caller without threading
  the struct through every call.
  """

  @enforce_keys []
  defstruct caller: nil, meta: nil, payload: nil

  @type t :: %__MODULE__{
          caller: pid() | nil,
          meta: term(),
          payload: term()
        }

  @process_key :cure_actor_state

  @doc """
  Normalise any of the accepted init shapes into an `%Actor.State{}` struct.

  Accepts:

    * an existing `%Cure.Actor.State{}` struct (returned as-is),
    * a keyword list with any of `:caller`, `:meta`, `:payload`,
    * a map with any of those string or atom keys,
    * any other term -- treated as a bare `:payload`.
  """
  @spec from_init(term()) :: t()
  def from_init(%__MODULE__{} = state), do: state

  def from_init(kv) when is_list(kv) do
    if Keyword.keyword?(kv) do
      %__MODULE__{
        caller: Keyword.get(kv, :caller),
        meta: Keyword.get(kv, :meta),
        payload: Keyword.get(kv, :payload)
      }
    else
      %__MODULE__{payload: kv}
    end
  end

  def from_init(%{} = map) do
    get = fn key ->
      Map.get(map, key) || Map.get(map, Atom.to_string(key))
    end

    %__MODULE__{
      caller: get.(:caller),
      meta: get.(:meta),
      payload: get.(:payload)
    }
  end

  def from_init(other), do: %__MODULE__{payload: other}

  @doc """
  Replace the struct's `:payload` with the value returned by a handler
  body. The handler may return either a full `%Cure.Actor.State{}` to
  replace the whole state, or any other term which is taken as the new
  payload.
  """
  @spec merge(t(), term()) :: t()
  def merge(%__MODULE__{} = _state, %__MODULE__{} = replacement), do: replacement
  def merge(%__MODULE__{} = state, bare), do: %__MODULE__{state | payload: bare}

  @doc "Send `message` to `state.caller` if one is registered; otherwise no-op."
  @spec notify(t(), term()) :: term()
  def notify(%__MODULE__{caller: caller}, message) when is_pid(caller) do
    send(caller, message)
  end

  def notify(%__MODULE__{}, _message), do: :no_caller

  @doc false
  @spec register_self(t()) :: t()
  def register_self(%__MODULE__{} = state) do
    Process.put(@process_key, state)
    state
  end

  @doc false
  @spec current() :: t() | nil
  def current, do: Process.get(@process_key)

  @doc """
  Send `message` to the caller registered for the current actor
  process. Used by the `notify/1` helper made available inside handler
  bodies.
  """
  @spec notify_self(term()) :: term()
  def notify_self(message) do
    case current() do
      %__MODULE__{} = state -> notify(state, message)
      _ -> :no_caller
    end
  end
end
